version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 8080:8080
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always  
    ports:
    - '9200:9200'
    - '9300:9300'